import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.stream.Collectors;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public List<String> slowFoxes(List<String> words) {



        List<String> actual = words
                                .stream()
                                .filter(abc -> !"Swift Fox".equals((String)abc))
                                .collect(Collectors.toList());


        return actual;

    }


    public List<Person> adult(List<Person> persons) {



                    //return Arrays.asList();

                return persons;




    }
}
